[workspace]

resolver = "2"

members = ["crates/website"]

[workspace.dependencies]
anyhow = "1.0.86"
dominator = "0.5.36"
dominator-css-bindgen = { git = "https://github.com/JedimEmO/dwind.git", rev = "92999258f0569cb46f7eeccfdd780a22cae2f4cd" }
dwind = { git = "https://github.com/JedimEmO/dwind.git", rev = "92999258f0569cb46f7eeccfdd780a22cae2f4cd" }
dwui = { git = "https://github.com/JedimEmO/dwind.git", rev = "92999258f0569cb46f7eeccfdd780a22cae2f4cd" }
dwind-macros = { git = "https://github.com/JedimEmO/dwind.git", rev = "92999258f0569cb46f7eeccfdd780a22cae2f4cd" }
futures = "0.3.30"
futures-signals = "0.3.34"
glam = { version = "0.29.2" }
js-sys = "0.3.70"
log = "0.4.22"
web-sys = { version = "0.3.70", features = ["CanvasRenderingContext2d", "HtmlCanvasElement", "Storage", "Clipboard", "WebGl2RenderingContext", "WebGlShader", "WebGlProgram", "WebGlBuffer", "WebGlVertexArrayObject", "WebGlUniformLocation"] }
wasm-bindgen = "0.2.93"
wasm-bindgen-futures = "0.4.43"
wasm-log = "0.3.1"